name: yuknanem
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  font_awesome_flutter: ^10.1.0
  introduction_screen: ^3.0.2
  lints: ^2.0.0
  lottie: ^1.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/yuknanem.png"
  min_sdk_android: 21r
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf

  assets:
    - assets/animations/
    - assets/images/
